version: '3.9'

services:
  python:
    image: python:latest
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: Python.Dockerfile
    volumes:
      - ./:/root/code
      - .vscode-server:/root/.vscode-server
  mlflow:
    command: mlflow server -h 0.0.0.0 --gunicorn-opts "--timeout 300"
    # command: tail -f /dev/null
    image: mlflow:latest
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    volumes:
      - ./_mlflow:/mlflow
    ports:
      - 5000:5000